### ISSUE TITLE
Gem versions?

### ISSUE THREAD

**Issue by maralik** [netguru/devise-ios-rails#12]
Hi I have this config:
rails (4.1.13)
devise-ios-rails (1.0.1)

And getting the SimpleTokenAuthentication::FallbackAuthenticationHandler (NameError) #9 error
https://github.com/netguru/devise-ios-rails/issues/9

How to update devise-ios-rails to version 1.8.0 or 1.10.0? When I specify 
gem "devise-ios-rails", "1.8.0"

I get "Could not find gem 'devise-ios-rails (= 1.8.0) ruby' in any of the gem sources listed in your Gemfile or available on this machine."

Any ideas?

Thanks

David

**Comment by willc0de4food** [comment]
Neither of those version exist for the gem.
To see a list of available versions, execute the following:
`$ gem list devise-ios-rails --remote --all`
