### ISSUE TITLE
No support for Rails 5

### ISSUE THREAD

**Issue by willc0de4food** [netguru/devise-ios-rails#19]
I realize that Rails 5 is only in beta at the moment, but the RC is planned for the 16th of this month, and the final release is tentatively scheduled for the 23rd. I would like to use this gem with a Rails 5 application since they've added API-only support into the Rails base. Is there a plan for getting this gem updated to work with Rails 5?

Thanks

**Comment by pharmaceutics** [comment]
Tested the gem with Rails 5 beta4 and looks like everything works fine, so I'm loosening dependency to < 5.1
