### ISSUE TITLE
Undefined path helpers in password controller

### ISSUE THREAD

**Issue by andrerobnagel** [netguru/devise-ios-rails#2]
### Environment:
* Rails version 4.1.5
* Devise version 3.4.1
* Devise iOS rails version 1.0.0
* Mac OSX Yosemite 10.10.2

I'm getting **NameError in DeviseIosRails::Passwords#new** when I access *http://localhost:3000/password/new*. The path helper functions are undefined, as seen in the attached image.

All of the path helpers in both the layout file and the view files are undefined. If one *link_to* method with a path helper method is removed, the error will occur at the next one. The password reset pages are the only ones where this happens. This doesn't happen if *devise_for* is used instead of *devise_ios_rails_for* in the routes file.

However, replacing all of the path helper functions with absolute strings, or prepending

    Rails.application.routes.url_helpers.

to the path helper method fixes it.

![devise ios rails error](https://cloud.githubusercontent.com/assets/8183102/6765628/83a814ba-cfae-11e4-94dc-2806021d7e45.png)

**Comment by blase** [comment]
Thanks for reporting @andrerobnagel, however I cannot reproduce your issue. Can you provide us a sample application where this error occurs?

**Comment by andrerobnagel** [comment]
I made a new barebones application with just devise and devise-ios-rails. It can be downloaded [here](https://drive.google.com/file/d/0BzB6Djs6tUGIYUo2bEJxaWFWQjA/view?usp=sharing). The error should occur when following the link to /password/new.

**Comment by bartoszkopinski** [comment]
Hi @andrerobnagel, sorry for the delay. Could you try updating to 1.0.1? The issue should be solved now. Thanks for reporting.
