### ISSUE TITLE
uninitialized constant DeviseIosRails::RegistrationsController::User

### ISSUE THREAD

**Issue by montekaka** [netguru/devise-ios-rails#4]
I keep getting error message like this
![ios](https://cloud.githubusercontent.com/assets/1149779/7853018/9101b57e-04bc-11e5-8290-313f0c52c158.png)

**Comment by blase** [comment]
@montekaka there's a bug that prevents naming Devise model other than "User". I'm working on it. Thanks for reporting.

**Comment by blase** [comment]
It's fixed on master branch. Still need to update the gem.
