### ISSUE TITLE
`devise_ios_rails_for` and `devise_for` at the same time?

### ISSUE THREAD

**Issue by TangRufus** [netguru/devise-ios-rails#8]
I am making a iOS app for my current Rails app.
How can i use `devise_ios_rails_for` and `devise_for` at the same time?

**Comment by ghilead** [comment]
If you don't pass other options to ``devise_for``, you can just replace the call to ``devise_for`` with ``devise_ios_rails_for``.

Otherwise, you could just pass extra options like you would normally do. For instance:
```ruby
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_ios_rails_for :users, controllers: {sessions: 'sessions'}
```
