### ISSUE TITLE
SimpleTokenAuthentication::FallbackAuthenticationHandler (NameError)

### ISSUE THREAD

**Issue by zsan** [netguru/devise-ios-rails#9]
Hi,

I tried this gem and i got

```sh
=> Booting Puma
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/home/zak/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/devise-ios-rails-1.0.1/lib/devise-ios-rails.rb:46:in `block in <class:Railtie>': uninitialized constant SimpleTokenAuthentication::FallbackAuthenticationHandler (NameError)
...
...
```

I downgraded `simple_token_authentication` to 1.8.0 (from 1.10.0) and everything is okay

**Comment by sunsidew** [comment]
@zsan That problem will be solved with this pull request.
https://github.com/netguru/devise-ios-rails/pull/6

**Comment by wherewelive** [comment]
Also getting this error with 1.10.0

**Comment by aswinramakrish** [comment]
@zsan Downgrading to 1.8.0 worked for me as well. Thanks!

**Comment by tjaklitsch** [comment]
How did you actually downgrade? I specified gem 'simple_token_authentication', '~> 1.8' in my gemfile and ran bundle update simple_token_authentication, and I still end up with 1.10 in my lock file
